backend/evote/urls.py
from django.conf.urls import url
# from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^accounts/password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('add_type/', views.add_type, name="add_type"),
    path('', views.list_types, name="list_types"),

    url(r'^coordinates', views.CoordinatesList.as_view()),    
    url(r'^types', views.TypeList.as_view()),   
    url(r'^proposals', views.ProposalList.as_view()), 
    url(r'^votings', views.VotingList.as_view()),    
    url(r'^options', views.OptionsList.as_view()),    
    url(r'^login', views.LoginList.as_view()),    
    url(r'^districts', views.DistrictList.as_view()),    
    url(r'^proposal', views.ProposalGet.as_view()),
    url(r'^option', views.OptionUpdate.as_view()),
    url(r'^isochrones', views.IsochroneList.as_view()),
    url(r'^users', views.UserList.as_view()),  
    url(r'^user-proposals', views.UserProposalList.as_view()),    
    url(r'^user-options', views.UserOptionList.as_view()),    
    url(r'^user', views.UserGet.as_view()),    
    url(r'^list-delegation', views.DelegationList.as_view()),    
    url(r'^update-delegations', views.CreateUpdateDelegationList.as_view()),    


    
    # url(r'^signup/$', views.signup, name='signup'),
    # url(r'^create_proposal/$', views.createProposal, name='create_proposal'),
    # url(r'^create_type/$', views.createType, name='create_type'),

    path('accounts/', include('django.contrib.auth.urls')),
    
    # url(r'^join_proposal/(?P<proposal_id>\d+)/$', views.joinProposal, name='join_proposal'),
    # url(r'^list_proposals/$', views.listProposals, name='list_proposals'),
    # url(r'^list_votings/$', views.listVotings, name='list_votings'),
    # url(r'^my_votings/$', views.myVotings, name='my_votings'),
    # url(r'^my_proposals/$', views.myProposals, name='my_proposals'),

    # url(r'^display_proposal/(?P<proposal_id>\d+)/$', views.displayProposal, name='display_proposal'),
    # url(r'^display_voting/(?P<proposal_id>\d+)/$', views.displayProposal, name='display_voting'),


]

backend/evote/models.py
from _datetime import datetime, timedelta

from dateutil.relativedelta import relativedelta
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _

MAJORITY_AGE = 18
OLDEST_AGE = 150

def validate_date(date):
    years = relativedelta( datetime.now(), date).years
    
    if years< MAJORITY_AGE or years> OLDEST_AGE:
        majority_age_year= datetime.now() - relativedelta(years=MAJORITY_AGE)
        oldest_age_year= datetime.now() - relativedelta(years=OLDEST_AGE)

        raise ValidationError("User age must be between {} and {}.\n So birthdate must be between {} and {}".format(MAJORITY_AGE, OLDEST_AGE,majority_age_year.date(),oldest_age_year.date()))
    
class District(models.Model):
    name = models.CharField(max_length=200, unique=True)
    def __str__(self):
        return self.name

class DistrictCoordinates(models.Model):
    lat = models.FloatField()
    lng = models.FloatField()
    subdistrict = models.IntegerField()
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True, blank=True)

class Voter(AbstractUser):
    """User model."""

    email = models.EmailField(_('email address'), unique=True)
    first_name = models.CharField(_('first name'), max_length=30, blank = False)
    last_name = models.CharField(_('last name'), max_length=150, blank = False)
    bio = models.TextField(null = True)
    photo = models.URLField(null =True)
    birthdate  = models.DateField(validators=[validate_date])
    karma = models.FloatField(default=1)
    district = models.ForeignKey(District, on_delete=models.CASCADE, null=True)
    
    REQUIRED_FIELDS = ['password','email','first_name', 'last_name','birthdate']
    
    def __str__(self):
        return self.username

    

        
    
class Type(models.Model):
    name = models.CharField(max_length=80)
    description = models.TextField(max_length=1000)
    url = models.URLField(null =True, blank = True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True, blank=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, related_name='children',related_query_name='child' , blank = True)
    isGeographical = models.BooleanField()
    lastUpdated =  models.DateTimeField(null = True)
    range1 = models.IntegerField(null=True, blank = True)
    range2 = models.IntegerField(null=True, blank = True)
    range3 = models.IntegerField(null=True, blank=True)

    class Meta:
        unique_together = ('name', 'district',)
    def __str__(self):
        return self.name
    def clean(self):
        if len(self.name) > 80:
            raise ValidationError('El nombre no puede tener más de 80 caracteres')
        if len(self.description) > 1000:
            raise ValidationError('La descripción puede tener más de 1000 caracteres')
        if not((self.url and self.range1 and self.range2 and self.range3) or (not self.url and not self.range1 and not self.range2 and not self.range3)):
            raise ValidationError('Si se introduce la url es necesario introducir los 3 rangos')
        
class Proposal(models.Model):
    title = models.CharField(max_length=80)
    description = models.TextField(max_length=1000)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True, blank=True)
    creator = models.ForeignKey(Voter, on_delete=models.SET_NULL, null=True, blank=True, related_name="created_proposals")
    type = models.ForeignKey(Type, on_delete=models.SET_NULL, null=True, blank=True)
    voter = models.ManyToManyField(Voter, blank = True, related_name="signed_proposals")
    creationDate =  models.DateTimeField(auto_now_add=True)
    votingStartDate = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.title
    
class Option(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    
    voting = models.ForeignKey(Proposal, on_delete=models.SET_NULL, null=True)
    creator = models.ForeignKey(Voter, on_delete=models.SET_NULL, null=True, related_name='options_creator')
    voter = models.ManyToManyField(Voter, related_name='options_voter')
    
    class Meta:
        unique_together = ('voting', 'creator',)
    def __str__(self):
        return self.name

class Coordinates(models.Model):
    lat = models.DecimalField(decimal_places=6, max_digits=12)
    lng = models.DecimalField(decimal_places=6, max_digits=12)
    range = models.IntegerField(null=True)
    polygon = models.IntegerField(null=True)
    innerPolygon = models.IntegerField(null=True)
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True, blank=True)
    option = models.ForeignKey(Option, on_delete=models.CASCADE, null=True)


class Delegation(models.Model):

    voter = models.ForeignKey(Voter, on_delete=models.CASCADE, related_name='delegations_voter')
    delegator = models.ForeignKey(Voter, on_delete=models.CASCADE, related_name='delegations_delegator')
    type = models.ForeignKey(Type, on_delete=models.CASCADE, null=True, blank=True)

backend/evote/forms.py
'''
Created on 9 dic. 2018

@author: Manue
'''
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UsernameField
from django.utils.translation import gettext_lazy as _

from evote.models import Voter, Proposal, Option, Type

class TypeForm(forms.ModelForm):
    divideDistrict = forms.BooleanField( required=False)
    class Meta:
        model = Type
        fields = ("name","description","isGeographical","url","range1","range2","range3")
        labels = {"name":"Nombre"}
    def clean(self):
        cleaned_data = super(TypeForm, self).clean()
        getUrl = cleaned_data.get("url")
        getRange1 = cleaned_data.get("range1")
        getRange2 = cleaned_data.get("range2")
        getRange3 = cleaned_data.get("range3")
        if( getUrl or getRange1 or getRange2 or getRange3) and not (getUrl and getRange1 and getRange2 and getRange3):
            raise forms.ValidationError("Si se introduce la url es necesario introducir los 3 rangos")
        return cleaned_data

backend/evote/templates/create_type.html
{% extends 'registration/base.html' %}
{% load static %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/create_type.css' %}" type="text/css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}
{% block title %}Tipos de votación{% endblock %}

{% block content %}
<div id="form">
	<ol>
		<h3>Crear tipo</h3>
		<form method="POST" class="post-form" onsubmit="showLoader()">
			{% csrf_token %}
			
			<div class="row">
					<div class="column">
						{% if  form.errors.name %}
						<div class="error">El nombre es obligatorio y debe tener menos de 80 caracteres</div>
						{% endif %}

						<p>
							<label for="id_name">Nombre*</label><br>
							{{ form.name }}
						</p>
						{% if  form.errors.description %}
						<div class="error">La descripción es obligatoria y debe tener menos de 80 caracteres</div>
						{% endif %}
						<p>
							<label for="id_description">Descripción*</label><br>
							{{ form.description }}
						</p>
					
						<p>
							{{ form.divideDistrict }}
							<label for="id_divideDistrict">División por distritos</label>
						</p>
						<input type="submit" class="save btn btn-default" value="Guardar"></input>

					</div>
					<div class="column">
							
							<p>
								{{ form.isGeographical }}
								<label for="id_isGeographical">¿Es geográfico?</label>
							</p>
							{% if  form.non_field_errors %}
								<div class="error">Si se introduce la url es necesario introducir los 3 rangos</div>
							{% endif %}
							<p>
								<label for="id_url">Url</label><br>
								{{ form.url }}
							</p>
							<p>
								<label for="id_range1">Rango más cercano (en segundos)</label><br>
								{{ form.range1 }}
							</p>
							<p>
								<label for="id_range2">Rango intermedio (en segundos)</label><br>
								{{ form.range2 }}
							</p>
							<p>
								<label for="id_range3">Rango más lejano (en segundos)</label><br>
								{{ form.range3 }}
							</p>
					</div>

				  </div>
		</form>
	</ol>
</div>
	<script type="text/javascript"> 
	 	var isGeo = $("#id_isGeographical")
		
		function checkGeo() {
			if(!isGeo.is(":checked")){
				$("#id_url").prop('disabled', true)
				$("#id_range1").prop('disabled', true) 
				$("#id_range2").prop('disabled', true) 
				$("#id_range3").prop('disabled', true) 
			}else{
				$("#id_url").prop('disabled', false)
				$("#id_range1").prop('disabled', false) 
				$("#id_range2").prop('disabled', false) 
				$("#id_range3").prop('disabled', false) 
			}
	  	}
		  checkGeo()
		  isGeo.on("change", checkGeo);
	 </script>
<div class="loader" id="loader" style="display:none"></div>

{% endblock %}

backend/evote/templates/list_types.html
{% extends 'registration/base.html' %}
{% load static %}
{% load render_table from django_tables2 %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'django_tables2/themes/paleblue/css/screen.css' %}" />
<link rel="stylesheet" href="{% static 'css/list_types.css' %}" type="text/css" />
{% endblock %}
{% block title %}Tipos de votación{% endblock %}

{% block content %}
	<h2>Lista de tipos</h2>
	<a href="/add_type" class="createButton">+ Crear tipo</a>
	<br>
	{% render_table table  %}	
{% endblock %}